// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: jifrvkbzojziouberpwc

class SupabaseConfig {
  static const String supabaseUrl = 'https://jifrvkbzojziouberpwc.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppZnJ2a2J6b2p6aW91YmVycHdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwOTU2OTIsImV4cCI6MjA3NDY3MTY5Mn0.bTCGVqsrXDJAgOZ21cVuiNBuVBD_JpjWxRDcrTgjgKo';
}
